### ISSUE TITLE
UPS counter

### ISSUE THREAD

**Issue by BurAndBY** [Olezen/UnitySourceMovement#22]
Please add UPS counter.

**Comment by PapersTheKingOfPapers** [comment]
I've made a UPS Counter, its pretty simple.

You just need a UI Text element, edit abit of the SurfController.cs, Player object requires SurfCharacter.cs and have the player object be tagged "Player".

1.
In SurfController.cs change on line 10

private ISurfControllable _surfer;

to

[HideInInspector] public ISurfControllable _surfer;

2.
Add the UPSCounter to the canvas object and reference the Text element to it

3. Enjoy
[UPSCounter.1.0.0.zip](https://github.com/Olezen/UnitySourceMovement/files/7941151/UPSCounter.1.0.0.zip)

**Comment by PapersTheKingOfPapers** [comment]
What, no thanks or anything?

**Comment by BurAndBY** [comment]
Thanks! Sorry, I did not notice this message.
